### ISSUE TITLE
No MCP PCB found, only MC4 PCB found

### ISSUE THREAD

**Issue by xilihutu888** [icub-tech-iit/electronics-boards-public#1]
![1200px-Cards](https://user-images.githubusercontent.com/20624124/105466680-9011bf80-5ccf-11eb-9aa5-2f32c579e4e6.jpg)
Can all the electronic circuit boards of iCub robot download PCB?
How do I have access to complete download

**Comment by maggia80** [comment]
> ![1200px-Cards](https://user-images.githubusercontent.com/20624124/105466680-9011bf80-5ccf-11eb-9aa5-2f32c579e4e6.jpg)
> Can all the electronic circuit boards of iCub robot download PCB?
> How do I have access to complete download

Hi @nan2854 the MCP are the old version of the motor control boards. The current iCub is using MC4-plus, EMS4 and 2FOC. They have ethernet connection and a much more powerful microcontroller

**Comment by xilihutu888** [comment]
> > ![1200px-Cards](https://user-images.githubusercontent.com/20624124/105466680-9011bf80-5ccf-11eb-9aa5-2f32c579e4e6.jpg)
> > Can all the electronic circuit boards of iCub robot download PCB?
> > How do I have access to complete download
> 
> Hi @nan2854 the MCP are the old version of the motor control boards. The current iCub is using MC4-plus, EMS4 and 2FOC. They have ethernet connection and a much more powerful microcontroller

Thank you for your reply.
Please specify which PDF file is the installation guide of ICub3.0 electronic circuit board, what are the specifications of the battery pack of ICub3.0, and please give us the specific welding process.
I would like to know the complete iCuB 3.0 assembly process guide, this is what I need the most help

**Comment by MrAndrea** [comment]
Hi @nan2854, you can find wiring schematics and BOMs at the following link:
https://github.com/icub-tech-iit/electronics-wiring-public/tree/master/icub3

Regarding the electronic boards, you can find information about schematic, PCB, assembly, BOM, layer stack up, etc., at:
https://github.com/icub-tech-iit/electronics-boards-public

**Comment by xilihutu888** [comment]
> Hi @nan2854, you can find wiring schematics and BOMs at the following link:
> https://github.com/icub-tech-iit/electronics-wiring-public/tree/master/icub3
![image](https://user-images.githubusercontent.com/20624124/105675144-97c9a200-5f23-11eb-9ba6-fcb30b1f9cf1.png)

![image](https://user-images.githubusercontent.com/20624124/105674052-e70ed300-5f21-11eb-8309-94b0701da0ec.png)
Thank you for your reply.
Where can you download the PCB information of the BMS electronic circuit board of the iCub robot battery pack?
How to weld the internal circuit of the battery pack?
HSM electronic circuit board information where can be downloaded?

How to get complete icub electronic circuit board PCB information? The open source information is incomplete, unable to manufacture icub independently, please help me
@MrAndrea

**Comment by xilihutu888** [comment]
hi @MrAndrea
Thank you for your reply.
Where can you download the PCB information of the BMS electronic circuit board of the iCub robot battery pack?
How to weld the internal circuit of the battery pack?
HSM electronic circuit board information where can be downloaded?

How to get complete icub electronic circuit board PCB information? The open source information is incomplete, unable to manufacture icub independently, please help me
![image](https://user-images.githubusercontent.com/20624124/106099890-609eff00-6176-11eb-8f36-9843cf903bc7.png)

**Comment by MrAndrea** [comment]
Hello @nan2854,
the battery pack was designed with this particular shape to fit the iCub's backpack, and the BMS is a standard electronic board not developed by us. In the following documents you will find more info about the mechanics and the electronics.

- Mechanics [REF.10s3pNCR18650ASC01 REV03.pdf](https://github.com/icub-tech-iit/electronics-boards-public/files/5885386/REF.10s3pNCR18650ASC01.REV03.pdf)
- BMS [PCM-L12S35-514.pdf](https://github.com/icub-tech-iit/electronics-boards-public/files/5885384/PCM-L12S35-514.pdf)
- Battery cell [PANASONIC-RIC-LI-ION-NCR-18650A.pdf](https://github.com/icub-tech-iit/electronics-boards-public/files/5885392/PANASONIC-RIC-LI-ION-NCR-18650A.pdf)
-  Battery Charger `165-10802-470` [Nova-360SR LiIon_48V.pdf](https://github.com/icub-tech-iit/electronics-boards-public/files/5885439/Nova-360SR.LiIon_48V.pdf)

**Comment by xilihutu888** [comment]
Hi @MrAndrea
thank you for your reply
I checked the icub open source hardware information and found it to be incomplete. How can I obtain complete hardware information to make my own icub robot? There are some discontinued products in the bill of materials. Where can I download the latest bill of materials, please help me.
![image](https://user-images.githubusercontent.com/20624124/106219921-61d33900-6215-11eb-8ec1-e70cb0b109ab.png)

**Comment by MrAndrea** [comment]
Hi @nan2854, I think there is something out of date. Can you send me the link where you extracted the BOM of the previous screenshot?

**Comment by xilihutu888** [comment]
Hi @MrAndrea ，thank you for your reply.
It is the bill of materials downloaded at this link (http://wiki.icub.org/wiki/Brushless_motors).
![123](https://user-images.githubusercontent.com/20624124/106829231-b3bd0880-66c6-11eb-9a42-6f3acc376294.png)

Where can I download the latest bill of materials, please help me.

**Comment by xilihutu888** [comment]
Hi @MrAndrea ，thank you for your reply.
It is the bill of materials downloaded at this link (http://wiki.icub.org/wiki/Brushless_motors).
