### ISSUE TITLE
Where can I download the electronic circuit board of PS-CPU_ELECTRONIC_BOARD.PRT in the head of iCub?

### ISSUE THREAD

**Issue by xilihutu888** [icub-tech-iit/electronics-boards-public#2]
Where can I download the electronic circuit board of PS-CPU_ELECTRONIC_BOARD.PRT in the head of iCub?
Clone all folders but no related electronic circuit boards were found.
![1](https://user-images.githubusercontent.com/20624124/111022611-b241d700-840e-11eb-834d-958763e87cc6.png)

**Comment by pattacini** [comment]
cc @MrAndrea

**Comment by maggia80** [comment]
Hi @nan2854, 

you can find the board here: https://github.com/icub-tech-iit/electronics-boards-public/tree/master/power-management/pscpu2

**Comment by xilihutu888** [comment]
Thank you for your reply
