### ISSUE TITLE
(CFA1, LMFC, FTC_001, FingerTip) These electronic circuit boards have not found corresponding folders and PCBs in the project. Please help me, thank you very much.

### ISSUE THREAD

**Issue by xilihutu888** [icub-tech-iit/electronics-boards-public#4]
(CFA1, LMFC, FTC_001, FingerTip) These electronic circuit boards have not found corresponding folders and PCBs in the project. Please help me, thank you very much.
![20210422140611](https://user-images.githubusercontent.com/20624124/115664773-db8e4500-a374-11eb-8f8b-5e4c20c64e0d.png)
![20210422140639](https://user-images.githubusercontent.com/20624124/115664787-e052f900-a374-11eb-8d15-0392fd006a75.png)
![20210422140715](https://user-images.githubusercontent.com/20624124/115664792-e2b55300-a374-11eb-8653-1dfd437eb883.png)

**Comment by pattacini** [comment]
cc @icub-tech-iit/silo-electr

**Comment by maggia80** [comment]
hi @xilihutu888 the board are:

CFA1: [https://github.com/icub-tech-iit/electronics-boards-public/tree/master/other-boards/can-filter](https://github.com/icub-tech-iit/electronics-boards-public/tree/master/other-boards/can-filter)

MAIS-FC: is in the same folder of the MAIS: [https://github.com/icub-tech-iit/electronics-boards-public/tree/master/sensor-boards/mais](https://github.com/icub-tech-iit/electronics-boards-public/tree/master/sensor-boards/mais)

FTC and FTC-con: [https://github.com/icub-tech-iit/electronics-boards-public/tree/master/other-boards/ftc](https://github.com/icub-tech-iit/electronics-boards-public/tree/master/other-boards/ftc) 

the fingertips are not released open-source yet

**Comment by xilihutu888** [comment]
hi @maggia80 
I have received the latest documentation information. Thank you very much for your reply. Is there any alternative to the iCub header (CCG012, COMe-cKL6)? Can I download the electronic circuit board (PCB, BOM)?

**Comment by maggia80** [comment]
CCG012 is the only one that fits and it's from [https://connecttech.com/](https://connecttech.com/) . The COM-express Compact Type 6 COMe-cKL6, could be replaced with any other **COMe Type 6 Compact** but we tested only this one. You need to pay attention to the heat sink, it must fit into the head.

**Comment by xilihutu888** [comment]
The problem has been solved, thank you for your reply.
